//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the branch must be provided in both English and French. .
        /// </summary>
        public static string BranchRequiredNameEnglish {
            get {
                return ResourceManager.GetString("BranchRequiredNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the branch must be provided in both English and French..
        /// </summary>
        public static string BranchRequiredNameFrench {
            get {
                return ResourceManager.GetString("BranchRequiredNameFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment needs to be greater than 0 character and less than 200 characters.
        /// </summary>
        public static string CommentLengthInvalid {
            get {
                return ResourceManager.GetString("CommentLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date for the activity is required..
        /// </summary>
        public static string EventRequiredDate {
            get {
                return ResourceManager.GetString("EventRequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description must be provided in both English and French..
        /// </summary>
        public static string EventRequiredDescriptionEnglish {
            get {
                return ResourceManager.GetString("EventRequiredDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description must be provided in both English and French..
        /// </summary>
        public static string EventRequiredDescriptionFrench {
            get {
                return ResourceManager.GetString("EventRequiredDescriptionFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the initiative in English is required..
        /// </summary>
        public static string InitiativeRequiredDescriptionEnglish {
            get {
                return ResourceManager.GetString("InitiativeRequiredDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the initiative in French is required..
        /// </summary>
        public static string InitiativeRequiredDescriptionFrench {
            get {
                return ResourceManager.GetString("InitiativeRequiredDescriptionFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An end date for the initiative is required..
        /// </summary>
        public static string InitiativeRequiredEndDate {
            get {
                return ResourceManager.GetString("InitiativeRequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the initiative must be provided in both English and French..
        /// </summary>
        public static string InitiativeRequiredNameEnglish {
            get {
                return ResourceManager.GetString("InitiativeRequiredNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the initiative must be provided in both English and French..
        /// </summary>
        public static string InitiativeRequiredNameFrench {
            get {
                return ResourceManager.GetString("InitiativeRequiredNameFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A start date for the initiative is required..
        /// </summary>
        public static string InitiativeRequiredStartDate {
            get {
                return ResourceManager.GetString("InitiativeRequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Timeline field is required..
        /// </summary>
        public static string InitiativeTimelineRequired {
            get {
                return ResourceManager.GetString("InitiativeTimelineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the region must be provided in both English and French. .
        /// </summary>
        public static string RegionRequiredNameEnglish {
            get {
                return ResourceManager.GetString("RegionRequiredNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the region must be provided in both English and French. .
        /// </summary>
        public static string RegionRequiredNameFrench {
            get {
                return ResourceManager.GetString("RegionRequiredNameFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all the options before printing..
        /// </summary>
        public static string ReportNoOptionSelected {
            get {
                return ResourceManager.GetString("ReportNoOptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists in our database..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address was not found in the Departmental Directory..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required to create a user..
        /// </summary>
        public static string UserRequiredEmail {
            get {
                return ResourceManager.GetString("UserRequiredEmail", resourceCulture);
            }
        }
    }
}
