//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date field is required..
        /// </summary>
        public static string EventRequiredDate {
            get {
                return ResourceManager.GetString("EventRequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Description field is required..
        /// </summary>
        public static string EventRequiredDescriptionEnglish {
            get {
                return ResourceManager.GetString("EventRequiredDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The French Description field is required..
        /// </summary>
        public static string EventRequiredDescriptionFrench {
            get {
                return ResourceManager.GetString("EventRequiredDescriptionFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Description field is required..
        /// </summary>
        public static string InitiativeRequiredDescriptionEnglish {
            get {
                return ResourceManager.GetString("InitiativeRequiredDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The French Description field is required..
        /// </summary>
        public static string InitiativeRequiredDescriptionFrench {
            get {
                return ResourceManager.GetString("InitiativeRequiredDescriptionFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End Date field is required..
        /// </summary>
        public static string InitiativeRequiredEndDate {
            get {
                return ResourceManager.GetString("InitiativeRequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Name field is required..
        /// </summary>
        public static string InitiativeRequiredNameEnglish {
            get {
                return ResourceManager.GetString("InitiativeRequiredNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The French Name field is required..
        /// </summary>
        public static string InitiativeRequiredNameFrench {
            get {
                return ResourceManager.GetString("InitiativeRequiredNameFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Date field is required..
        /// </summary>
        public static string InitiativeRequiredStartDate {
            get {
                return ResourceManager.GetString("InitiativeRequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Name field is required..
        /// </summary>
        public static string RegionBranchRequiredNameEnglish {
            get {
                return ResourceManager.GetString("RegionBranchRequiredNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The French Name field is required..
        /// </summary>
        public static string RegionBranchRequiredNameFrench {
            get {
                return ResourceManager.GetString("RegionBranchRequiredNameFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        public static string UserRequiredEmail {
            get {
                return ResourceManager.GetString("UserRequiredEmail", resourceCulture);
            }
        }
    }
}
