//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help you understand how various initiatives impact you, select a timeline and then your Region and branch below to generate a list of initiatives sorted by their impacts on you (high, medium, low, none or Blueprint 2020). Data will be updated regularly. Questions? &lt;a href=&apos;mailto:Teresa.martin@pwgsc-tpsgc.gc.ca?subject=TransformationTimelineTool&apos;&gt;Click here to send an email.&lt;/a&gt;.
        /// </summary>
        public static string AccessibilityIntroduction {
            get {
                return ResourceManager.GetString("AccessibilityIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed English Description.
        /// </summary>
        public static string ActivityDetailedDescEng {
            get {
                return ResourceManager.GetString("ActivityDetailedDescEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed French Description.
        /// </summary>
        public static string ActivityDetailedDescFra {
            get {
                return ResourceManager.GetString("ActivityDetailedDescFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/Home.
        /// </summary>
        public static string ApplicationHomeURL {
            get {
                return ResourceManager.GetString("ApplicationHomeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci c’est un message automatique.&lt;br/&gt;
        ///Votre poste a été approuver dans le Calendrier national G4des transformations.&lt;br/&gt;
        ///Veuillez utiliser &lt;a href=&apos;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&apos;&gt;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&lt;/a&gt; pour l’accèss au système.&lt;br/&gt;
        ///Si vous avez des questions ou croyez que vous avez reçu ce message par erreur, veuillez contacter &lt;a href=&apos;mailto:{2}&apos;&gt;l’administration&lt;/a&gt;.&lt;br/&gt;
        ///Le Calendrier national des transformations se trouve &lt;a href=&apos;{0}/?lang=fra&apos;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApprovedMailBody {
            get {
                return ResourceManager.GetString("ApprovedMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier des transformations: Votre poste a été approuver || Transformation Timeline Tool: Your item has been approved .
        /// </summary>
        public static string ApprovedMailSubject {
            get {
                return ResourceManager.GetString("ApprovedMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign an Approver.
        /// </summary>
        public static string AssignApprover {
            get {
                return ResourceManager.GetString("AssignApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Impact.
        /// </summary>
        public static string AssignImpact {
            get {
                return ResourceManager.GetString("AssignImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic.
        /// </summary>
        public static string Atlantic {
            get {
                return ResourceManager.GetString("Atlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP2020.
        /// </summary>
        public static string BP2020 {
            get {
                return ResourceManager.GetString("BP2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment.
        /// </summary>
        public static string CommentAdd {
            get {
                return ResourceManager.GetString("CommentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string CommentDayAgo {
            get {
                return ResourceManager.GetString("CommentDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string CommentDaysAgo {
            get {
                return ResourceManager.GetString("CommentDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string CommentHourAgo {
            get {
                return ResourceManager.GetString("CommentHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string CommentHoursAgo {
            get {
                return ResourceManager.GetString("CommentHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string CommentJustNow {
            get {
                return ResourceManager.GetString("CommentJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment needs to be greater than 0 character and less than 200 characters.
        /// </summary>
        public static string CommentLengthInvalid {
            get {
                return ResourceManager.GetString("CommentLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string CommentMinuteAgo {
            get {
                return ResourceManager.GetString("CommentMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string CommentMinutesAgo {
            get {
                return ResourceManager.GetString("CommentMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string CommentReply {
            get {
                return ResourceManager.GetString("CommentReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please contact the &lt;a href=&quot;mailto:teresa.martin@pwgsc-tpsgc.gc.ca&quot;&gt;administrator&lt;/a&gt; if you would like to add, change or remove an initiative or its information.&lt;/p&gt;.
        /// </summary>
        public static string ContactAdminToAddInit {
            get {
                return ResourceManager.GetString("ContactAdminToAddInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Activity.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string CreateBranch {
            get {
                return ResourceManager.GetString("CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Initiative.
        /// </summary>
        public static string CreateInitiative {
            get {
                return ResourceManager.GetString("CreateInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Region.
        /// </summary>
        public static string CreateRegion {
            get {
                return ResourceManager.GetString("CreateRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Choose an actual or estimate date for this activity.&lt;/li&gt;
        ///&lt;li&gt;The date selected will determine the placement of the activity icon along the transformation timeline.&lt;/li&gt;
        ///&lt;li&gt;The date itself will not be displayed to users of the Transformation Timeline Tool.&lt;/li&gt;&lt;/ul&gt;
        ///If you need assistance, please contact &lt;a href=mailto:teresa.martin@pwgsc-tpsgc.gc.ca&gt;the administrator&lt;/a&gt;..
        /// </summary>
        public static string EventDateInstr {
            get {
                return ResourceManager.GetString("EventDateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Description in English which is displayed when the user clicks on the icon for this activity. (optional field).
        /// </summary>
        public static string EventTextEng {
            get {
                return ResourceManager.GetString("EventTextEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed description in French which is displayed when the user clicks on the icon for this activity. (optional field).
        /// </summary>
        public static string EventTextFra {
            get {
                return ResourceManager.GetString("EventTextFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Name.
        /// </summary>
        public static string FrenchName {
            get {
                return ResourceManager.GetString("FrenchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Short Description (Required field).
        /// </summary>
        public static string HoverDescEng {
            get {
                return ResourceManager.GetString("HoverDescEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Short Description (Required Field).
        /// </summary>
        public static string HoverDescFra {
            get {
                return ResourceManager.GetString("HoverDescFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Write a short description in &lt;strong&gt;English&lt;/strong&gt; of the activitity that will be visible when users move their mouse pointer over the icon on the timeline. &lt;/p&gt;
        ///&lt;p&gt;If you will be providing in-depth information in the Full Description field below, please also include one of these phrases here: &lt;/p&gt;
        ///&lt;ul&gt;&lt;li&gt;Milestone activities use: (Click on the Red Dot icon to read more)&lt;/li&gt;
        ///&lt;li&gt;Training activities use: (Click on the Book icon to read more)&lt;/li&gt;&lt;/ul&gt;
        ///
        ///&lt;p&gt;Note:  You must complete the content in  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HoverInstrEng {
            get {
                return ResourceManager.GetString("HoverInstrEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact.
        /// </summary>
        public static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacts.
        /// </summary>
        public static string Impacts {
            get {
                return ResourceManager.GetString("Impacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Initiative in English.
        /// </summary>
        public static string InitEnglishDesc {
            get {
                return ResourceManager.GetString("InitEnglishDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Initiative in English.
        /// </summary>
        public static string InitEnglishName {
            get {
                return ResourceManager.GetString("InitEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Initiative in French.
        /// </summary>
        public static string InitFrenchDesc {
            get {
                return ResourceManager.GetString("InitFrenchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Initiative in French.
        /// </summary>
        public static string InitFrenchName {
            get {
                return ResourceManager.GetString("InitFrenchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        public static string Initiative {
            get {
                return ResourceManager.GetString("Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the Initiative.
        /// </summary>
        public static string InitiativeDescription {
            get {
                return ResourceManager.GetString("InitiativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiatives.
        /// </summary>
        public static string Initiatives {
            get {
                return ResourceManager.GetString("Initiatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one Initiative from the drop-down menu..
        /// </summary>
        public static string InitiativeSelectLabel {
            get {
                return ResourceManager.GetString("InitiativeSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edited by.
        /// </summary>
        public static string LastEditedBy {
            get {
                return ResourceManager.GetString("LastEditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string MonthApr {
            get {
                return ResourceManager.GetString("MonthApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string MonthAug {
            get {
                return ResourceManager.GetString("MonthAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string MonthDec {
            get {
                return ResourceManager.GetString("MonthDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string MonthFeb {
            get {
                return ResourceManager.GetString("MonthFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string MonthJan {
            get {
                return ResourceManager.GetString("MonthJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string MonthJul {
            get {
                return ResourceManager.GetString("MonthJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string MonthJun {
            get {
                return ResourceManager.GetString("MonthJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string MonthMar {
            get {
                return ResourceManager.GetString("MonthMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MonthMay {
            get {
                return ResourceManager.GetString("MonthMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string MonthNov {
            get {
                return ResourceManager.GetString("MonthNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string MonthOct {
            get {
                return ResourceManager.GetString("MonthOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string MonthSep {
            get {
                return ResourceManager.GetString("MonthSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Transformation Timeline Tool.
        /// </summary>
        public static string NationalTransformationTimelineTool {
            get {
                return ResourceManager.GetString("NationalTransformationTimelineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCA.
        /// </summary>
        public static string NCA {
            get {
                return ResourceManager.GetString("NCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Activities.
        /// </summary>
        public static string OfActivities {
            get {
                return ResourceManager.GetString("OfActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Branches.
        /// </summary>
        public static string OfBranches {
            get {
                return ResourceManager.GetString("OfBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Impacts.
        /// </summary>
        public static string OfImpacts {
            get {
                return ResourceManager.GetString("OfImpacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Initiatives.
        /// </summary>
        public static string OfInitiatives {
            get {
                return ResourceManager.GetString("OfInitiatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Regions.
        /// </summary>
        public static string OfRegions {
            get {
                return ResourceManager.GetString("OfRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Users.
        /// </summary>
        public static string OfUsers {
            get {
                return ResourceManager.GetString("OfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string Ontario {
            get {
                return ResourceManager.GetString("Ontario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific.
        /// </summary>
        public static string Pacific {
            get {
                return ResourceManager.GetString("Pacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci c’est un message automatique.&lt;br/&gt;
        ///Votre approbation est requise pour une poste dans le Calendrier national des transformations.&lt;br/&gt;
        ///Veuillez utiliser &lt;a href=&apos;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&apos;&gt;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&lt;/a&gt; pour l’accèss au système.&lt;br/&gt;
        ///Si vous avez des questions ou croyez que vous avez reçu ce message par erreur, veuillez contacter &lt;a href=&apos;mailto:{2}&apos;&gt;l’administration&lt;/a&gt;.&lt;br/&gt;
        ///Le Calendrier national des transformations se trouve &lt;a href=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PendingMailBody {
            get {
                return ResourceManager.GetString("PendingMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier des transformations: Nouvelles postes pour votre approbation  || Transformation Timeline Tool:  New items for your approval.
        /// </summary>
        public static string PendingMailSubject {
            get {
                return ResourceManager.GetString("PendingMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string Quebec {
            get {
                return ResourceManager.GetString("Quebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci c’est un message automatique.&lt;br/&gt;
        ///Un poste dans le Calendrier national des transformations n’était pas approuver. S’il vous plaît, contactez votre Approbateur.&lt;br/&gt;
        ///Veuillez utiliser &lt;a href=&apos;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&apos;&gt;{0}/Activites-Activities/Details?id={1}&amp;lang=fra&lt;/a&gt; pour l’accèss au système.&lt;br/&gt;
        ///Si vous avez des questions ou croyez que vous avez reçu ce message par erreur, veuillez contacter &lt;a href=&apos;mailto:{2}&apos;&gt;l’administration&lt;/a&gt;.&lt;br/&gt;
        ///Le Calendrier national des tra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RejectMailBody {
            get {
                return ResourceManager.GetString("RejectMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier des transformations: Votre poste était retourner pour révision  || Transformation Timeline Tool: Your item has been returned for revision.
        /// </summary>
        public static string RejectMailSubject {
            get {
                return ResourceManager.GetString("RejectMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Initiative.
        /// </summary>
        public static string ReportByInitiative {
            get {
                return ResourceManager.GetString("ReportByInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Quarter.
        /// </summary>
        public static string ReportByQuarterly {
            get {
                return ResourceManager.GetString("ReportByQuarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FY.
        /// </summary>
        public static string ReportFiscalYear {
            get {
                return ResourceManager.GetString("ReportFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Reports.
        /// </summary>
        public static string ReportPageTitle {
            get {
                return ResourceManager.GetString("ReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string ReportPrint {
            get {
                return ResourceManager.GetString("ReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Initiatives.
        /// </summary>
        public static string ReportPrintCoverPageAllInitiatives {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageAllInitiatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Report.
        /// </summary>
        public static string ReportPrintCoverPageInitiativeTitle {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageInitiativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ReportPrintCoverPageOverview {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Report.
        /// </summary>
        public static string ReportPrintCoverPageQuarterlyTitle {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageQuarterlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSPC Timeline Tool.
        /// </summary>
        public static string ReportPrintCoverPageSubtitle {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information contained in this report is accurate as of the date this report was printed. Please see the &lt;a href=&apos;http://transformation-intranet.tpsgc-pwgsc.gc.ca/?lang=eng&apos;&gt;PSPC Timeline Tool&lt;/a&gt; for up-to-date information..
        /// </summary>
        public static string ReportPrintCoverPageWarning {
            get {
                return ResourceManager.GetString("ReportPrintCoverPageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string ReportQuarter {
            get {
                return ResourceManager.GetString("ReportQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string ReportQuarterPrefix {
            get {
                return ResourceManager.GetString("ReportQuarterPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Initiative.
        /// </summary>
        public static string ReportSelectInitiative {
            get {
                return ResourceManager.GetString("ReportSelectInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quarter.
        /// </summary>
        public static string ReportSelectQuarter {
            get {
                return ResourceManager.GetString("ReportSelectQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Timeline.
        /// </summary>
        public static string ReportSelectTimeline {
            get {
                return ResourceManager.GetString("ReportSelectTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string ReportTimeline {
            get {
                return ResourceManager.GetString("ReportTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint 2020.
        /// </summary>
        public static string ReportTimelineBP2020 {
            get {
                return ResourceManager.GetString("ReportTimelineBP2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string ReportTimelineTransformation {
            get {
                return ResourceManager.GetString("ReportTimelineTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These Initiatives do not have any activities in the Timeline for this Quarter:.
        /// </summary>
        public static string ReportUnusedInitiatives {
            get {
                return ResourceManager.GetString("ReportUnusedInitiatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your region.
        /// </summary>
        public static string SelectYourArea {
            get {
                return ResourceManager.GetString("SelectYourArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your branch.
        /// </summary>
        public static string SelectYourBranch {
            get {
                return ResourceManager.GetString("SelectYourBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be significant changes to the way that an employee does their work..
        /// </summary>
        public static string TimelineHighImpact {
            get {
                return ResourceManager.GetString("TimelineHighImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To help you understand how various transformation initiatives impact you, select your Region and branch below to generate a list of initiatives sorted by their impacts on you (high, medium, low or none). Hold your mouse over the displayed icons to find links to information about the milestones or training being offered. Data will be updated regularly. Questions? &lt;a href=&apos;mailto:Teresa.martin@pwgsc-tpsgc.gc.ca?subject=TransformationTimelineTool&apos;&gt; Click here to send an email&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string TimelineIntroduction {
            get {
                return ResourceManager.GetString("TimelineIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be minimal changes to the way that an employee does their work..
        /// </summary>
        public static string TimelineLowImpact {
            get {
                return ResourceManager.GetString("TimelineLowImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be some changes to the way that an employee does their work..
        /// </summary>
        public static string TimelineMediumImpact {
            get {
                return ResourceManager.GetString("TimelineMediumImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be no changes to the way that an employee does their work..
        /// </summary>
        public static string TimelineNoImpact {
            get {
                return ResourceManager.GetString("TimelineNoImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan.
        /// </summary>
        public static string Timespan {
            get {
                return ResourceManager.GetString("Timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string TrainingPlural {
            get {
                return ResourceManager.GetString("TrainingPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation Timeline Tool.
        /// </summary>
        public static string TransformationTimelineTool {
            get {
                return ResourceManager.GetString("TransformationTimelineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        public static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
    }
}
