//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Timeline {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Timeline() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Timeline", typeof(Timeline).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To help you understand how various initiatives impact you, select a timeline and then your Region and branch below to generate a list of initiatives sorted by their impacts on you (high, medium, low, none or Blueprint 2020). Hold your mouse over the displayed icons to find links to information about the milestones or training being offered. Data will be updated regularly. Questions? &lt;a href=&apos;mailto:Teresa.martin@pwgsc-tpsgc.gc.ca?subject=TransformationTimelineTool&apos;&gt; Click here to send an email&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint 2020: Initiatives are generally wide-reaching and may have department-wide applications..
        /// </summary>
        public static string BlueprintImpact {
            get {
                return ResourceManager.GetString("BlueprintImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be significant changes to the way that an employee does their work..
        /// </summary>
        public static string HighImpact {
            get {
                return ResourceManager.GetString("HighImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;../Images/book.png&apos; class=&apos;align-middle&apos; style=&apos;width:24px; height: 32px;&apos; /&gt; &lt;span&gt;&amp;nbsp;Training&lt;/span&gt;&lt;br /&gt; &lt;img src=&apos;../Images/circle.png&apos; class=&apos;align-middle&apos; style=&apos;width:24px; height: 32px;&apos; /&gt; &lt;span&gt;&amp;nbsp;Milestone&lt;/span&gt;.
        /// </summary>
        public static string IconLegend {
            get {
                return ResourceManager.GetString("IconLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This transformation timeline tool has been designed to provide you with a list of the current transformation initiatives based on the area and the branch that you have chosen. After you close this message, the tool will display a re-sorted list of initiatives that have been organized based on the degree to which they will change the way you do your work.&lt;/p&gt; &lt;p&gt;Within your displayed results, click on the name of the initiative to read more about what it is and how it generally impacts employees.  You can [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InitialFilterSplash {
            get {
                return ResourceManager.GetString("InitialFilterSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be minimal changes to the way that an employee does their work..
        /// </summary>
        public static string LowImpact {
            get {
                return ResourceManager.GetString("LowImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be some changes to the way that an employee does their work..
        /// </summary>
        public static string MediumImpact {
            get {
                return ResourceManager.GetString("MediumImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be no changes to the way that an employee does their work..
        /// </summary>
        public static string NoImpact {
            get {
                return ResourceManager.GetString("NoImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
